spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/personal
    username: root
    password: root1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    date-format: yyyy-MM-dd
    time-zone: GMT+8
    serialization:
      write-dates-as-timestamps: true
mybatis:
  mapperLocations : classpath:com/example/iblog/dao/*.xml
  configuration:
    mapUnderscoreToCamelCase: true
